add some debugging output to this guy

diff --git a/eng/pipelines/templates/stages/archetype-js-release.yml b/eng/pipelines/templates/stages/archetype-js-release.yml
--- a/eng/pipelines/templates/stages/archetype-js-release.yml
+++ b/eng/pipelines/templates/stages/archetype-js-release.yml
@@ -236,49 +236,70 @@ stages:
     variables:
       - template: /eng/pipelines/templates/variables/globals.yml
     jobs:
+      - job: Dump values
+        pool:
+          name: $(LINUXPOOL)
+          image: $(LINUXVMIMAGE)
+          os: linux
+        steps:
+          - pwsh: |
+              Write-Host "variables.SetDevVersion: $(SetDevVersion)"
+              Write-Host "variables.Build.Reason: $(Build.Reason)"
+              Write-Host "variables.System.TeamProject: $(System.TeamProject)"
+            displayName: Dumping Values
       - ${{ each artifact in parameters.Artifacts }}:
-          - ${{if and(ne(artifact.skipPublishDevFeed, 'true'), or(eq(variables['SetDevVersion'], 'true'), and(eq(variables['Build.Reason'],'Schedule'), eq(variables['System.TeamProject'], 'internal'))))}}:
-            - job: DetectPackageArchive_${{ replace(artifact.name, '-', '_') }}
-              variables:
-                - template: /eng/pipelines/templates/variables/image.yml
-              pool:
-                name: $(LINUXPOOL)
-                image: $(LINUXVMIMAGE)
-                os: linux
-              displayName: 'Detecting package archive_${{artifact.name}}'
-              steps:
-              - checkout: self
-              - download: current
-              - pwsh: |
-                  $detectedPackageName=Get-ChildItem $(Pipeline.Workspace)/${{parameters.ArtifactName}}/${{artifact.name}}/*.tgz
-                  Write-Host "Detected package name: $($detectedPackageName)"
-                  if ($detectedPackageName -notmatch "-alpha")
-                  {
-                    Write-Error "Found non alpha version artifact to publish as dev version. Failing publish step. VersionPolicy should be client or core in rush.json to get alpha version build."
-                    exit 1
-                  }
-                  echo "##vso[task.setvariable variable=Package.Archive]$detectedPackageName"
-                  if ('$(Build.Repository.Name)' -eq 'Azure/azure-sdk-for-js') {
-                    $npmToken="$(azure-sdk-npm-token)"
-                    $registry="${{parameters.Registry}}"
-                  }
-                  else {
-                    $npmToken="$(azure-sdk-devops-npm-token)"
-                    $registry="${{parameters.PrivateRegistry}}"
-                  }
-                  echo "##vso[task.setvariable variable=NpmToken]$npmToken"
-                  echo "##vso[task.setvariable variable=Registry]$registry"
-                displayName: Detecting package archive_${{artifact.name}}
-            - template: /eng/pipelines/templates/jobs/npm-release-task.yml
-              parameters:
-                Artifact: ${{artifact}}
-                Registry: ${{parameters.Registry}}
-                PathToArtifacts: $(Pipeline.Workspace)/${{parameters.ArtifactName}}/${{artifact.name}}
-                VarDependencies:
-                  Tag: "dev"
-                Environment: 'none'
-                DependsOn:
-                  - DetectPackageArchive_${{ replace(artifact.name, '-', '_') }}
+        - job: Dump values for ${{ artifact.name }}
+          pool:
+            name: $(LINUXPOOL)
+            image: $(LINUXVMIMAGE)
+            os: linux
+          steps:
+            - pwsh: |
+                Write-Host "Artifact.skipPublishDevFeed: ${{ parameters.Artifact.skipPublishDevFeed }}"
+              displayName: Dumping artifact values
+      - ${{ each artifact in parameters.Artifacts }}:
+        - ${{if and(ne(artifact.skipPublishDevFeed, 'true'), or(eq(variables['SetDevVersion'], 'true'), and(eq(variables['Build.Reason'],'Schedule'), eq(variables['System.TeamProject'], 'internal'))))}}:
+          - job: DetectPackageArchive_${{ replace(artifact.name, '-', '_') }}
+            variables:
+              - template: /eng/pipelines/templates/variables/image.yml
+            pool:
+              name: $(LINUXPOOL)
+              image: $(LINUXVMIMAGE)
+              os: linux
+            displayName: 'Detecting package archive_${{artifact.name}}'
+            steps:
+            - checkout: self
+            - download: current
+            - pwsh: |
+                $detectedPackageName=Get-ChildItem $(Pipeline.Workspace)/${{parameters.ArtifactName}}/${{artifact.name}}/*.tgz
+                Write-Host "Detected package name: $($detectedPackageName)"
+                if ($detectedPackageName -notmatch "-alpha")
+                {
+                  Write-Error "Found non alpha version artifact to publish as dev version. Failing publish step. VersionPolicy should be client or core in rush.json to get alpha version build."
+                  exit 1
+                }
+                echo "##vso[task.setvariable variable=Package.Archive]$detectedPackageName"
+                if ('$(Build.Repository.Name)' -eq 'Azure/azure-sdk-for-js') {
+                  $npmToken="$(azure-sdk-npm-token)"
+                  $registry="${{parameters.Registry}}"
+                }
+                else {
+                  $npmToken="$(azure-sdk-devops-npm-token)"
+                  $registry="${{parameters.PrivateRegistry}}"
+                }
+                echo "##vso[task.setvariable variable=NpmToken]$npmToken"
+                echo "##vso[task.setvariable variable=Registry]$registry"
+              displayName: Detecting package archive_${{artifact.name}}
+          - template: /eng/pipelines/templates/jobs/npm-release-task.yml
+            parameters:
+              Artifact: ${{artifact}}
+              Registry: ${{parameters.Registry}}
+              PathToArtifacts: $(Pipeline.Workspace)/${{parameters.ArtifactName}}/${{artifact.name}}
+              VarDependencies:
+                Tag: "dev"
+              Environment: 'none'
+              DependsOn:
+                - DetectPackageArchive_${{ replace(artifact.name, '-', '_') }}
 
       - job: PublishDocsToNightlyBranch
         variables:
