job

diff --git a/eng/pipelines/templates/stages/archetype-js-release.yml b/eng/pipelines/templates/stages/archetype-js-release.yml
--- a/eng/pipelines/templates/stages/archetype-js-release.yml
+++ b/eng/pipelines/templates/stages/archetype-js-release.yml
@@ -224,46 +224,46 @@ stages:
     variables:
       - template: /eng/pipelines/templates/variables/globals.yml
     jobs:
-      - job: PublishPackages
-        condition: or(eq(variables['SetDevVersion'], 'true'), and(eq(variables['Build.Reason'],'Schedule'), eq(variables['System.TeamProject'], 'internal')))
-        displayName: Publish package to daily feed
-        pool:
-          name: azsdk-pool-mms-ubuntu-2004-general
-          image: azsdk-pool-mms-ubuntu-2004-1espt
-          os: linux
-        steps:
-          - checkout: self
-          - download: current
-            artifact: ${{parameters.ArtifactName}}
-            timeoutInMinutes: 5
-          - ${{ each artifact in parameters.Artifacts }}:
-              - ${{if ne(artifact.skipPublishDevFeed, 'true')}}:
-                  - pwsh: |
-                      $detectedPackageName=Get-ChildItem $(Pipeline.Workspace)/${{parameters.ArtifactName}}/${{artifact.name}}/*.tgz
-                      Write-Host "Detected package name: $($detectedPackageName)"
-                      if ($detectedPackageName -notmatch "-alpha")
-                      {
-                        Write-Error "Found non alpha version artifact to publish as dev version. Failing publish step. VersionPolicy should be client or core in rush.json to get alpha version build."
-                        exit 1
-                      }
-                      echo "##vso[task.setvariable variable=Package.Archive]$detectedPackageName"
-                      if ('$(Build.Repository.Name)' -eq 'Azure/azure-sdk-for-js') {
-                        $npmToken="$(azure-sdk-npm-token)"
-                        $registry="${{parameters.Registry}}"
-                      }
-                      else {
-                        $npmToken="$(azure-sdk-devops-npm-token)"
-                        $registry="${{parameters.PrivateRegistry}}"
-                      }
-                      echo "##vso[task.setvariable variable=NpmToken]$npmToken"
-                      echo "##vso[task.setvariable variable=Registry]$registry"
-                    displayName: Detecting package archive_${{artifact.name}}
-                  - template: /eng/pipelines/templates/steps/npm-release-task.yml
-                    parameters:
-                      Artifact: ${{artifact}}
-                      Registry: ${{parameters.Registry}}
-                      PathToArtifacts: $(Pipeline.Workspace)/${{parameters.ArtifactName}}/${{artifact.name}}
-                      Tag: "dev"
+    - ${{ each artifact in parameters.Artifacts }}:
+      - ${{if ne(artifact.skipPublishDevFeed, 'true')}}:
+        - job: PrePublishPackages
+          condition: or(eq(variables['SetDevVersion'], 'true'), and(eq(variables['Build.Reason'],'Schedule'), eq(variables['System.TeamProject'], 'internal')))
+          displayName: Pre Publish package to daily feed
+          pool:
+            name: azsdk-pool-mms-ubuntu-2004-general
+            image: azsdk-pool-mms-ubuntu-2004-1espt
+            os: linux
+          steps:
+            - checkout: self
+            - download: current
+              artifact: ${{parameters.ArtifactName}}
+              timeoutInMinutes: 5
+            - pwsh: |
+                $detectedPackageName=Get-ChildItem $(Pipeline.Workspace)/${{parameters.ArtifactName}}/${{artifact.name}}/*.tgz
+                Write-Host "Detected package name: $($detectedPackageName)"
+                if ($detectedPackageName -notmatch "-alpha")
+                {
+                  Write-Error "Found non alpha version artifact to publish as dev version. Failing publish step. VersionPolicy should be client or core in rush.json to get alpha version build."
+                  exit 1
+                }
+                echo "##vso[task.setvariable variable=Package.Archive]$detectedPackageName"
+                if ('$(Build.Repository.Name)' -eq 'Azure/azure-sdk-for-js') {
+                  $npmToken="$(azure-sdk-npm-token)"
+                  $registry="${{parameters.Registry}}"
+                }
+                else {
+                  $npmToken="$(azure-sdk-devops-npm-token)"
+                  $registry="${{parameters.PrivateRegistry}}"
+                }
+                echo "##vso[task.setvariable variable=NpmToken]$npmToken"
+                echo "##vso[task.setvariable variable=Registry]$registry"
+              displayName: Detecting package archive_${{artifact.name}}
+        - template: /eng/pipelines/templates/steps/npm-release-task.yml
+          parameters:
+            Artifact: ${{artifact}}
+            Registry: ${{parameters.Registry}}
+            PathToArtifacts: $(Pipeline.Workspace)/${{parameters.ArtifactName}}/${{artifact.name}}
+            Tag: "dev"
 
       - job: PublishDocsToNightlyBranch
         condition: and(succeeded(), or(eq(variables['SetDevVersion'], 'true'), and(eq(variables['Build.Reason'],'Schedule'), eq(variables['System.TeamProject'], 'internal'),  ne(variables['Skip.PublishDocs'], 'true'))))
